config/routes.rb
Backjubu::Application.routes.draw do
  get "users/signup"
  post "users/signup_complete"

  get "users/login"
  post "users/login_complete"
  get "users/logout_complete"
	resources :posts do
		resources :comments, shallow: true
		resources :rates, shallow: true
	end
	
	root 'posts#index'
	get "/rating" => 'posts#show_rating'	
	get "/rating/:category"=> 'posts#show_category_rating'
	get "/:category" => 'posts#show_category'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :post
	validates :content, :presence => {:message =>"내용을 입력하세요."}
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments, dependent: :destroy
	has_many :rates, dependent: :destroy
	validates :category, :inclusion => { :in => ["한식","외국음식","간식","술"], :message =>"한식, 외국음식, 간식, 술 중 하나를 선택하셔야 합니다."}
	validates :title, :presence => {:message =>"제목을 입력하세요." }
	validates :content, :presence => {:message=>"내용을 입력하세요."}
	mount_uploader :image, ImageUploader
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :comments
	has_many :rates
	validates :username, :presence => {:message =>"아이디를 입력하세요"}
	validates :username, :uniqueness => {:message =>"이미 존재하는 아이디입니다.", :case_sensitive => false}
	validates :password, :length => { :minimum => 3, :too_showrt => "비밀번호는 최소 3자 이상입니다."}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :login_check, :only => [:create, :destroy]
  def create
		@post=Post.find(params[:post_id])
		@comment=@post.comments.new(comment_params)
		if @comment.save
			flash[:alert]="댓글이 달렸습니다."
			redirect_to post_path(@post)
		else 
			flash[:alert]=@comment.errors.values.flatten.join(' ')
			redirect_to post_path(@post)
		end
  end


  def destroy
		@comment=Comment.find(params[:id])
		@post=@comment.post
		if session[:user_id]==@comment.user_id
			@comment.destroy
			flash[:alert]="댓글이 삭제되었습니다."
			redirect_to post_path(@post)
		else 
			flash[:alert]="권한이 없습니다"
			redirect_to :back
		end
  end
	private
		def comment_params
			params.require(:comment).permit(:content, :user_id)
		end

  def edit
  end

  def update
  end

	def login_check
		@current_id=nil
		if !session[:user_id].nil?
			@current_id=session[:user_id]
		else
			redirect_to '/users/login'
		end
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	http_basic_authenticate_with name: "admin", password: "1131", only: [:destroy,:edit]
	before_action :login_check
	skip_before_action :login_check, :only => [:index,:show,:show_category,:destroy,:edit]
  def index
		@posts=Post.all
  end

  def show
		@post=Post.find(params[:id])
		@comments=@post.comments
		@current_user=User.where(id: session[:user_id])[0]
		@rate=@post.rates
		rate_average
		@current_rate=@post.rates.where(user_id:@current_user.try(:id)).first
	
  end

  def show_category
		case params[:category]
		when "korean"
			@category="한식"
		when "liquid"
			@category="술"
		when "snack"
			@category="간식"
		else
			@category="외국음식"
		end
		@posts=Post.where(category:@category)
  end

	def show_rating
		@posts=Post.order(:rating)
		render action: 'index'
	end
	def show_category_rating
		show_category
		@posts=@posts.order(:rating)
		render action: 'show_category'
	end
  def new
		@post=Post.new
  end

  def edit
		@post=Post.find(params[:id])
  end

  def create
		@post=Post.new(post_params)
		if @post.save
			flash[:alert]="글이 작성되었습니다"
			redirect_to(@post)
		else
			flash[:alert]=@post.errors.values.flatten.join(' ')
			redirect_to :back
		end
  end

  def update
		@post=Post.find(params[:id])
		if  @post.update(post_params)
			flash[:alert]="수정되었습니다."
			redirect_to @post
		else
			flash[:alert]=@post.errors.values.flatten.join(' ')
			redirect_to :back
		end
  end

  def destroy
		@post=Post.find(params[:id])
		@post.destroy

		redirect_to posts_path
  end

	private
		def post_params
			params.require(:post).permit(:title,:content,:category,:image)
		end
 	
	def rate_average
		if @post.try(:rating)
			@rate_average=@post.rating
		else 
			@rate_average="평가가 없습니다"
		end
	end
	
	def login_check
		@current_user =nil
		if !session[:user_id].nil?
			@current_user=User.find(session[:user_id])
		else
			redirect_to "/users/login"
		end
	end
end

app/controllers/rates_controller.rb
class RatesController < ApplicationController
	before_action :login_check, :only => [:create, :update]
	after_action :post_rating, :only => [:create, :update]
	def create
		@post=Post.find(params[:post_id])
		@rate=@post.rates.new(rate_params)
		if @rate.save
			flash[:alert]="평가에 참여하셨습니다."
			redirect_to post_path(@post)
		else
			flash[:alert]=@comment.errors.values.flatten.join(' ')
			redirect_to post_path(@post)
		end
	end

	def update
		@rate=Rate.find(params[:id])
	if	@rate.update(rate_params)
			flash[:alert]="평가를 수정하였습니다."
			redirect_to :back 
		else
			flash[:alert]=@comment.errors.values.flatten.join(' ')
			redirect_to :back 
		end
	end


	private 
		def rate_params
			params.require(:rate).permit(:user_id,:rating)
		end


 	def post_rating
		@rate.post.update(rating:
	(@rate.post.rates.average(:rating)*10).to_i/10.0)
	end


	def login_check
		@current_id=nil
		if !session[:user_id].nil?
			@current_id=session[:user_id]
		else
			redirect_to '/users/login'
		end
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def signup
		@user=User.new
  end

  def signup_complete
		@user=User.new(params.require(:user).permit(:username,:password))
		if params[:user][:password]!=params[:user][:retype_password]
			flash[:alert]="비밀번호가 다릅니다"
			redirect_to :back
		elsif @user.save
			flash[:alert]="회원가입 되었습니다."
			redirect_to('/')
		else
			flash[:alert]=@user.errors.values.flatten.join(' ')
			redirect_to :back
		end
  end

  def login
		@user=User.new
  end

  def login_complete
		user=User.where(params[:user])[0]
		if user.nil?
			flash[:alert]="아이디 또는 비밀번호를 잘못 입력하셨습니다."
			redirect_to :back
		else
			session[:user_id]=user.id
			flash[:alert]="성공적으로 로그인하였습니다."
			redirect_to '/'
		end
  end

  def logout_complete
		reset_session
		flash[:alert]="로그아웃 되었습니다."
		redirect_to "/"
  end

	def login_check
		@current_user = nil
		if !session[:user_id].nil?
			@current_user=User.find(session[:user_id])
		else
			redirect_to "/users/login"
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/rates_helper.rb
module RatesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<% if !comment.nil? %>
<p>
	<strong>작성자:</strong>
	<%= comment.user.username %>

	<strong>Comment:</strong>
	<%= comment.content%>
	<% if comment.user.id == session[:user_id] %>
	<%= link_to '삭제하기', comment_path(comment), method: :delete, data: { confirm:"삭제할까요?"} %>
	<% end %>
</p>
<% else %>
<% end %>

app/views/comments/_form.html.erb
<%= form_for([@post,@post.comments.build]) do |f| %>
	<% if !@current_user.nil? %> 
	<%= f.hidden_field :user_id,value:@current_user.id %>
	<% end %>
	<div class="form-inline">
	<%= f.text_area :content ,placeholder: "댓글을 달아주세요", class:"form-control"%>
	
	<%= f.submit "댓글달기", class: "btn btn-default " %>
	</div>
<% end %>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/comments/edit.html.erb
<h1>Comments#edit</h1>
<p>Find me in app/views/comments/edit.html.erb</p>

app/views/comments/index.html.erb
<h1>Comments#index</h1>
<p>Find me in app/views/comments/index.html.erb</p>

app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>

app/views/comments/show.html.erb
<h1>Comments#show</h1>
<p>Find me in app/views/comments/show.html.erb</p>

app/views/comments/update.html.erb
<h1>Comments#update</h1>
<p>Find me in app/views/comments/update.html.erb</p>

app/views/layouts/_header.html.erb
<div class="container">
	<h1 id="backjubu-title"><a id="backjubu-title-link" href="/">백주부 모아보기</a></h1>
</div>
<nav class="navbar navbar-default">
	<div class="container">
		<div class="navbar-header">
			<button class="navbar-toggle collapsed" data-toggle="collapse" data-target="#target">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
		</div>
		<div class="collapse navbar-collapse" id="target">
			<ul class="nav navbar-nav">
				<li><a href="/">전체보기</a></li>
				<li><a href="/korean">한식</a></li>
				<li><a href="/western">양식</a></li>
				<li><a href="/snack">간식</a></li>
				<li><a href="/liquid">술</a></li>
			</ul>
			<ul class="nav navbar-nav navbar-right">		
			<% if session[:user_id].nil? %>
				<li><a href="/users/login">로그인</a></li> 
				<li><a href="/users/signup">회원가입</a></li>
			<% else %>
				<li><a href="/users/logout_complete">로그아웃</a></li>
			<% end %>
			</ul>
		</div>
	</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Backjubu</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">


</head>
<body>
<%= render :partial => 'layouts/header.html.erb' %>
<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post, html: {multipart: true }  do |f| %>
	<%= f.label :category %>:
	<%= f.select(:category, [['한식','한식'],['외국음식','외국음식'],['간식','간식'],['술','술']]) %>
	<br>
 	<%= f.label :title %>:
	<%= f.text_field :title %><br />

	<%= f.label :content %>:
	<%= f.text_area :content %><br />
	
	<%= f.label :image %>:
	<%= f.file_field :image %><br />
	<%=f.submit %>
<% end %>

app/views/posts/_show.html.erb
<% @posts.reverse.each do |post| %>
	<div class="col-md-4">
		<a href="/posts/<%=post.id%>"><img class="img-responsive" src="<%=post.image_url(:thumb) %>"></a>
		<h3><a href="/posts/<%=post.id%>"><%=post.title %>
<% if !post.rating.nil? %><span class="badge"><%=post.rating%></span><% end %></a></h3>
<p><span class="label label-warning"><%= post.category %></span></p>
</div>
<% end %>

app/views/posts/create.html.erb
<h1>Post#create</h1>
<p>Find me in app/views/post/create.html.erb</p>

app/views/posts/destroy.html.erb
<h1>Post#destroy</h1>
<p>Find me in app/views/post/destroy.html.erb</p>

app/views/posts/edit.html.erb
<p><%= flash[:alert] %></p>
<h2>요리  수정하기</h2>

<%= render :partial =>'posts/form' %>
<p>
<%= link_to '돌아가기', @post %></p>

app/views/posts/edit_complete.html.erb
<h1>Post#edit_complete</h1>
<p>Find me in app/views/post/edit_complete.html.erb</p>

app/views/posts/index.html.erb
<div class="container">
	<% if !flash[:alert].nil? %>
	<div class="alert alert-danger">
		<%= flash[:alert] %>
	</div>
	<% end %>
</div>
<div class="container">
	<div class="row">
	<%= render :partial => 'posts/show' %>
</div>

app/views/posts/new.html.erb
<p><%= flash[:alert] %></p>
<h2>요리 추가하기</h2>

<%= render :partial =>'posts/form' %>

app/views/posts/new_complete.html.erb
<h1>Post#new_complete</h1>
<p>Find me in app/views/post/new_complete.html.erb</p>

app/views/posts/show.html.erb
<div class="container">
	<% if !flash[:alert].nil? %>
		<div class="alert alert-danger">
		<%= flash[:alert] %>
		</div>
	<% end %>
	<h2 class="text-center">음식 정보 보기</h2>
	<div class="row">
		<div class="col-md-1">
		</div>
		<div class="col-md-5 text-right">
			<img src="<%= @post.image_url(:medium) %>">
		</div>
		<div class="col-md-5">
			<h3>+<%= @post.title %></h3>
			<p><span class="label label-warning"><%= @post.category %></span></p>
			<p>평점: <%= @rate_average %> (<%= @rate.count %>명 참여) </p><span><%= render 'rates/form' %></span>
			<p>내용: <%= @post.content %></p>
			<p><%= link_to '수정하기', edit_post_path(@post) %> | <%= link_to '삭제하기', post_path(@post), :method => :delete, data: {confirm: '삭제하시겠습니까?'} %></p>
			<p><%= link_to '전체 리스트 가기',posts_path %></p>
			<hr />
			<h2>Comments</h2>
				<%= render @post.comments %>
			<h2>Add a comment:</h2>
			<%= render 'comments/form' %>
		</div>
		<div class="col-md-1">
		</div>
</div>

app/views/posts/show_category.html.erb
<div class="container">


<%= render :partial => 'posts/show' %>
</div>

app/views/posts/update.html.erb
<h1>Post#update</h1>
<p>Find me in app/views/post/update.html.erb</p>

app/views/rates/_form.html.erb
<% if @current_rate.nil? %>
	<%= form_for([@post,@post.rates.build]) do |f| %>

	<%= f.hidden_field :user_id,value:@current_user.try(:id) %>

	<%= f.select(:rating, [['1',1],['2',2],['3',3],['4',4],['5',5]]) %>
	<%= f.submit "평가 참여하기", class:"btn btn-xs btn-default" %>
<% end %>
<% else %>
	<%= form_for @current_rate do |f| %>
	<%= f.hidden_field :user_id,value:@current_user.try(:id) %>

	<%= f.select(:rating, [['1',1],['2',2],['3',3],['4',4],['5',5]]) %>
	<%= f.submit "평가 수정하기", class: "btn btn-xs btn-default" %>
<% end %>
<% end %>

app/views/users/login.html.erb
<div class="container">
<% if !flash[:alert].nil? %>
<div class="alert alert-danger"> 
<%= flash[:alert] %>
</div>
<%end%>
</div>
<div class="container">
	<div class="row">
		<div class="col-md-4">
		</div>
		<div class="text-center col-md-4">
			<h3 class="form-heading">로그인하기</h3>
			<h3></h3>
			<%= form_for @user, url:{action:'login_complete'} do |f| %>
			<p><%= f.text_field :username, class: "form-control", placeholder: "아이디" %></p>
			<p><%= f.text_field :password, class: "form-control", placeholder: "비밀번호" %></p>
			<p><%= f.submit "로그인", class: "btn btn-lg btn-block" %></p>
			<% end %>
		</div>
		<div class="col-md-4">
		</div>
	</div>
</div>

app/views/users/login_complete.html.erb
<h1>Users#login_complete</h1>
<p>Find me in app/views/users/login_complete.html.erb</p>

app/views/users/logout_complete.html.erb
<h1>Users#logout_complete</h1>
<p>Find me in app/views/users/logout_complete.html.erb</p>

app/views/users/signup.html.erb
<div class="container">
	<% if !flash[:alert].nil? %>
	<div class="alert alert-danger"><%= flash[:alert] %></div>
	<% end %>
</div>
<div class="container">
	<div class="row">
		<div class="col-md-4">
		</div>
		<div class="col-md-4 text-center">
		
			<h3 class="form-heading">회원 가입</h3>
			<h3> </h3>
			<%= form_for @user, url:{action: 'signup_complete'} do |f| %>
			<p><%= f.text_field :username, placeholder: "아이디",class: "form-control" %></p>
			<p><%= f.password_field :password, placeholder: "비밀번호", class: "form-control" %></p>
			<p><%= f.password_field :retype_password, placeholder: "비밀번호확인", class: "form-control" %></p>
			<p><%= f.submit "가입하기", class: "btn btn-lg btn-block" %>
			<% end %>	
		</div>
		<div class="col-md-4">
		</div>
	</div>
</div>

app/views/users/signup_complete.html.erb
<h1>Users#signup_complete</h1>
<p>Find me in app/views/users/signup_complete.html.erb</p>